[package]
name = "hephaestus"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "1.44.2", features = ["macros", "time", "rt-multi-thread"] }
winapi = { version = "0.3.9", features = ["winuser", "processthreadsapi"] }
